#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

# Run
if [ ! -d test ]; then
    mkdir test
fi

base=test/test
n=0
target=${base}_${n}
while [ -d $target ]; do
    n=$(( $n + 1 ))
    target=${base}_${n}
done

cp -r topAir $target
mergeMeshes $target -addCases '(leftSolid heater rightSolid bottomWater)'

#------------------------------------------------------------------------------
